name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update backend and restart PM2 process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/alex/Documents/Gamech/Uniclubs-Server
            git pull origin main
            npm install
            pm2 restart uniclubs-server